#!/bin/sh

source $(dirname $0)/config

(echo " $@"; sleep $DURATION)\
| lemonbar \
        -f "$FONT1"\
	-f "$FONT2"\
        -F "$COLOR_FOREGROUND"\
        -B "#00FFFFFF"\
        -g "$NOTIFY_GEOMETRY"\
        -u $LINEHEIGHT
