#!/bin/bash
source $(dirname $0)/config

# WIFI ICONS
# 

QUAL=`iwconfig wlp3s0 | grep 'Link Quality=' | awk '{gsub(/[=/]/," "); print $3}'`
MAX=`iwconfig wlp3s0 | grep 'Link Quality=' | awk '{gsub(/[=/]/," "); print $4}'`
PERC=`echo $QUAL*100/$MAX | bc`
if [ $(cat /sys/class/net/enp0s25/operstate) = "up" ]; then
  PERC=cable
fi
icon=""
case $PERC in
	[0-4])
		icon=""
	;;
	[4-9])
		icon=""
	;;
	[2-3]*)
		icon=""
	;;
	[4-5]*)
		icon=""
	;;
	[6-7]*)
		icon=""
	;;
	cable)
		icon=""	
	;;
	*)
		icon=""
	;;
esac

echo "%{F$COLOR_ICON}$icon%{F-}%"
