#!/bin/sh

bspc config border_width        2
bspc config window_gap          2

for monitor in $(bspc query -M); do
bspc monitor $monitor \
        -d $monitor/{i,ii,iii,iv,v,vi,vii,viii,ix,x}
done

bspc config top_padding 16 

# Visual options
bspc config split_ratio         0.50
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#332d29"
bspc config active_border_color "#5a4f48"
bspc config focused_border_color "#504339"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Rules
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a astime sticky=on
bspc rule -a feh floating=on manage=off
bspc rule -a steam desktop=^10

compton --shadow-exclude 'n:a:Conky' -b &
mpd &
$HOME/.config/bspwm/panel/panel | $HOME/.config/bspwm/panel/clickable
