#!/bin/sh

err() {
  echo "$1"
  exit 1
}

usage() {
  echo "usage: monitor [option] [argument]"
  echo
  echo "Options:"
  echo "     laptop - Only laptop monitor"
  echo "     vga - Only VGA monitor"
  echo "     mirror   - mirror"
  echo "     -h, --help     - display this"
  exit
}

#Argument Parsing
case "$1" in
  'laptop')
    	$HOME/.screenlayout/laptop.sh
    	bspc monitor LVDS1 -d LVDS1/{i,ii,iii,iv,v,vi,vii,viii,ix,x}
    	$HOME/.config/bspwm/panel/notify %{F#32CD32}%{F-} Laptop
   	;;
  'vga')
    	while [ $(xrandr | grep -w VGA1  | awk -F'[ +]' '{print $2}') != "connected" ]
    	do
		echo "wait";
    	done
    	$HOME/.screenlayout/vga.sh
    	bspc monitor VGA1 -d VGA1/{i,ii,iii,iv,v,vi,vii,viii,ix,x}
    	$HOME/.config/bspwm/panel/notify %{F#32CD32}%{F-} External
    	;;
  'mirror')
    	xrandr --output "LVDS1" --auto --output "VGA1" --auto --same-as LVDS1 --output "DP1" --auto --same-as LVDS1
    	$HOME/.config/bspwm/panel/notify %{F#32CD32}%{F-} Mirror
    	;;
  'normal')
	if [[ `xrandr | grep " connected" | grep "VGA"` ]]; then
        	 $HOME/.screenlayout/normal.sh
	fi
	for monitor in $(bspc query -M); do
		bspc monitor $monitor \
			        -d $monitor/{i,ii,iii,iv,v,vi,vii,viii,ix,x}
	done
	$HOME/.config/bspwm/panel/notify %{F#32CD32}%{F-} Normal
    	;;
  ''|'-h'|'--help')
    usage
    ;;
  *)
    err "Unrecognized option \`$1', see dvol --help"
    ;;
esac
