#!/bin/sh

sxhkd &
bspwm
compton --vsync opengl-swc --shadow-exclude 'n:a:Conky' -b &
#while true ; do
#	sxhkd &
#	[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
#	mkfifo "$PANEL_FIFO"
#	bspwm -s "$PANEL_FIFO" -p W || break
#done
