# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1439072772);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1439072892);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1439113966);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1439072652);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1439113846);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 29);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.search.countryCode", "SK");
user_pref("browser.search.region", "SK");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150807021757");
user_pref("browser.slowStartup.averageTime", 1276);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20150807021757");
user_pref("browser.startup.homepage_override.mstone", "39.0.3");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":3}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1439158131786");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1439072124314");
user_pref("datareporting.policy.firstRunTime", "1439071731785");
user_pref("datareporting.sessions.current.activeTicks", 6);
user_pref("datareporting.sessions.current.firstPaint", 1209);
user_pref("datareporting.sessions.current.main", 168);
user_pref("datareporting.sessions.current.sessionRestored", 1392);
user_pref("datareporting.sessions.current.startTime", "1439121472766");
user_pref("datareporting.sessions.current.totalTime", 31);
user_pref("datareporting.sessions.currentIndex", 5);
user_pref("datareporting.sessions.previous.0", "{\"s\":1439071731315,\"a\":5,\"t\":30,\"c\":false,\"m\":67,\"fp\":1259,\"sr\":1414}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1439072112737,\"a\":5,\"t\":30,\"c\":false,\"m\":164,\"fp\":1399,\"sr\":1531}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1439072291637,\"a\":79,\"t\":37418,\"c\":true,\"m\":165,\"fp\":1033,\"sr\":1200}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1439110125834,\"a\":204,\"t\":7148,\"c\":false,\"m\":164,\"fp\":1126,\"sr\":1294}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1439121190649,\"a\":6,\"t\":26,\"c\":false,\"m\":177,\"fp\":1197,\"sr\":1452}");
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:39.0.3");
user_pref("extensions.getAddons.cache.lastUpdate", 1439072773);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "39.0.3");
user_pref("extensions.lastPlatformVersion", "39.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"39.0.3\",\"st\":1438915354000,\"mt\":1438915343000}}}");
user_pref("gecko.buildID", "20150807021757");
user_pref("gecko.mstone", "39.0.3");
user_pref("idle.lastDailyNotification", 1439117445);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1439072354);
user_pref("media.gmp-gmpopenh264.version", "1.4");
user_pref("media.gmp-manager.buildID", "20150807021757");
user_pref("media.gmp-manager.lastCheck", 1439072354);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1439121472);
user_pref("toolkit.telemetry.previousBuildID", "20150807021757");
